[package]
edition = "2018"
name = "flv-k8-spg"
version = "1.0.0"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Fluvio SPG for K8"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"


[dependencies]
log = "0.4.8"
serde = "1.0.76"
serde_derive = "1.0.76"
serde_json = "1.0.27"
serde_qs = "0.4.1"
flv-types = { version = "0.2.0", path ="../../types" }
k8-obj-metadata = { version = "1.0.0" }
flv-k8-spu = { version = "1.0.0", path = "../metadata-spu"}

