[package]
name = "flv-k8-partition"
version = "1.0.0"
edition = "2018"
authors = ["Fluvio Contributors <team@fluvio.io>"]
description = "Fluvio Partition for K8"
repository = "https://github.com/infinyon/fluvio"
license = "Apache-2.0"


[dependencies]
log = "0.4.8"
serde = { version ="1.0.103", features = ['derive'] }
serde_json = "1.0.27"
k8-obj-metadata = { version = "1.0.0" }