name: CI NG

on:
  push:
    branches: [ci_ng]
  workflow_dispatch:

jobs:
  cancel_previous_runs:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.4.1
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}

  megatest:
    name: Megatest
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-2
      AWS_DEFAULT_REGION: us-east-2
      EC2_AMI: ami-0a3bb968cc36aa314
    steps:
    - run: ssh-keygen -t RSA -f id_rsa
    - run: aws ec2 import-key-pair --key-name fluvio-ci-$GITHUB_RUN_ID --public-key-material fileb://id_rsa.pub
    - run: |
        aws ec2 run-instances \
          --image-id $EC2_AMI \
          --instance-type m5.2xlarge \
          --security-group-ids sg-010f0a9ee7ddac50f \
          --key-name fluvio-ci-$GITHUB_RUN_ID \
          --query "Instances[0].InstanceId" \
          --output text > ec2_instance_id
    - run: cat ec2_instance_id
    - run: sleep 60
    - run: |
        aws ec2 describe-instances \
          --instance-ids $(cat ec2_instance_id) \
          --query "Reservations[0].Instances[0].PublicIpAddress" \
          --output text > ec2_instance_public_ip
    - run: cat ec2_instance_public_ip
    - run: echo 'SSH_ARGS="-o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@$(cat ec2_instance_public_ip)"' >> $GITHUB_ENV
    - run: echo $SSH_ARGS
    - run: ssh $SSH_ARGS 'echo test'
    - run: ssh $SSH_ARGS 'git clone https://github.com/infinyon/fluvio.git --depth 1'
    - if: always()
      run: aws ec2 terminate-instances --instance-ids $(cat ec2_instance_id)