name: CI NG

on:
  push:
    branches: [ci_ng]
  workflow_dispatch:

jobs:
  cancel_previous_runs:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.4.1
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}

  megatest:
    name: Megatest
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-2
      AWS_DEFAULT_REGION: us-east-2
      EC2_AMI: ami-012fd581fc7600f48
    steps:
    - run: curl -sSf https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$GITHUB_SHA/ci_ng.sh | bash
    - run: $SSH_EXEC_1 "git clone https://github.com/infinyon/fluvio.git --depth 1"
    - run: $SSH_EXEC "cargo make check-format"
    - run: $SSH_EXEC "cargo make clippy"
    - run: $SSH_EXEC "make build-all-test"
    - run: $SSH_EXEC "make run-all-unit-test"
    - run: $SSH_EXEC "make make run-all-doc-test"
    - run: $SSH_EXEC "helm version"
    - run: $SSH_EXEC "minikube version"
    - name: Local test
      run: $SSH_EXEC "minikube start --driver=docker --kubernetes-version 1.19.6"
    - run: sleep 30
    - run: $SSH_EXEC "minikube profile list"
    - run: $SSH_EXEC "minikube status"
    - run: $SSH_EXEC "make RELEASE=true build_test"
    - run: $SSH_EXEC "target/release/fluvio cluster start --setup --local --develop"
    - run: $SSH_EXEC "target/release/fluvio version"
    - run: $SSH_EXEC "make RELEASE=true UNINSTALL=noclean smoke-test-tls-root"
    - run: $SSH_EXEC "examples/tests/build.sh --release"
    - run: $SSH_EXEC "examples/tests/run.sh --release"
    - run: $SSH_EXEC "minikube delete"
    - name: K8 test
      run: $SSH_EXEC "minikube start --driver=docker --kubernetes-version 1.19.6"
    - run: $SSH_EXEC "nohup  minikube tunnel --alsologtostderr > /tmp/tunnel.out 2> /tmp/tunnel.out &"
    - run: sleep 30
    - run: $SSH_EXEC "minikube profile list"
    - run: $SSH_EXEC "minikube status"
    - run: $SSH_EXEC "make RELEASE=true TARGET=x86_64-unknown-linux-musl build_test"
    - run: $SSH_EXEC "make RELEASE=true TARGET=x86_64-unknown-linux-musl k8-setup"
    - run: $SSH_EXEC "make RELEASE=true minikube_image"
    - run: $SSH_EXEC "make RELEASE=true minikube_image"
    - run: $SSH_EXEC "make RELEASE=true TARGET=x86_64-unknown-linux-musl UNINSTALL=noclean smoke-test-k8-tls-root"
    - if: always()
      run: aws ec2 terminate-instances --instance-ids $EC2_INSTANCE_ID