name: Publish Latest Development Image

on: 
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  publish_image:
    name: Publish Latest Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Clang
        run: sudo apt install -y clang-10
      - name: Login to Docker Hub
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Publish latest development Fluvio Image
        run: make latest_image
        env:
          TARGET_CC: clang
